import { recordAppError } from "./error-system.js";
const parse = (value, fallback = []) => { try { return JSON.parse(value) ?? fallback; } catch { return fallback; } };
const safeText = (value) => value === null || value === undefined || value === "" ? "Non renseigné" : Array.isArray(value) ? (value.length ? value.join(", ") : "Aucun") : String(value);
const htmlEscape = (value) => safeText(value).replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const csvCell = (value) => { let text=safeText(value);if(/^[=+\-@]/.test(text))text=`'${text}`;return `"${text.replaceAll('"','""')}"`; };
const bytesToBase64 = (bytes) => { let binary="";for(let offset=0;offset<bytes.length;offset+=32768)binary+=String.fromCharCode(...bytes.subarray(offset,offset+32768));return btoa(binary); };
const ascii = (value) => new TextEncoder().encode(value);
const pdfText = (value) => safeText(value).normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^\x20-\x7E]/g,"?").replaceAll("\\","\\\\").replaceAll("(","\\(").replaceAll(")","\\)");
const wrap = (value, width=82) => { const words=pdfText(value).split(/\s+/),lines=[];let line="";for(const word of words){if((line+" "+word).trim().length>width){if(line)lines.push(line);line=word;}else line=(line+" "+word).trim();}if(line)lines.push(line);return lines.length?lines:[""]; };

export function createSummaryPdf(summary) {
  const lines=[];for(const [label,value] of summary.fields){const wrapped=wrap(`${label}: ${safeText(value)}`);lines.push(...wrapped);}
  const content=["q","0.09 0.22 0.40 rg","0 744 595 98 re f","1 1 1 rg","BT /F2 24 Tf 42 802 Td (WORKCRUTE) Tj ET","BT /F1 10 Tf 42 781 Td (RECRUTEMENT SIMPLE ET ORGANISE) Tj ET","0.08 0.13 0.22 rg","BT /F2 15 Tf 42 712 Td (Recapitulatif administratif) Tj ET","BT /F1 9 Tf 42 690 Td"];
  let y=0;for(const line of lines.slice(0,47)){content.push(`0 ${y? -14:0} Td (${pdfText(line)}) Tj`);y+=1;}content.push("ET","0.35 0.43 0.55 rg","BT /F1 8 Tf 42 40 Td (Document genere automatiquement par Workcrute - donnees professionnelles uniquement) Tj ET","Q");
  const stream=content.join("\n"),objects=[null,"<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>",`<< /Length ${ascii(stream).length} >>\nstream\n${stream}\nendstream`,`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>`,`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>`];
  let pdf="%PDF-1.4\n%Workcrute\n",offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=ascii(pdf).length;pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`;}const xref=ascii(pdf).length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)pdf+=`${String(offsets[i]).padStart(10,"0")} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return ascii(pdf);
}
export function createSummaryCsv(summary) { return `\uFEFFChamp,Valeur\r\n${summary.fields.map(([label,value])=>`${csvCell(label)},${csvCell(value)}`).join("\r\n")}\r\n`; }

async function candidateSummary(env,id){const row=await env.DB.prepare("SELECT u.id,u.email,u.created_at,p.* FROM users u JOIN candidate_profiles p ON p.user_id=u.id WHERE u.id=?").bind(id).first();if(!row)return null;const docs=(await env.DB.prepare("SELECT kind,original_name FROM documents WHERE user_id=? AND deleted_at IS NULL ORDER BY created_at").bind(id).all()).results||[],preferences=parse(row.preferences_json,{}),answers=parse(row.questionnaire_answers,{});return{kind:"candidate",name:`${row.first_name} ${row.last_name}`,fields:[["Date",row.created_at],["ID utilisateur",row.id],["Nom",row.last_name],["Prénom",row.first_name],["Email",row.email],["Téléphone",row.phone],["Ville",row.city],["Région",row.region],["Métier",row.professional_title],["Secteur",answers.domain||preferences.domain],["Expérience",parse(row.experience_json,[]).join(", ")||answers.experience],["Disponibilité",row.availability],["Contrat",preferences.contract||answers.contract],["Télétravail",preferences.workMode||answers.workMode],["Compétences",parse(row.skills_json,[]).join(", ")||answers.skills],["Documents ajoutés",docs.map(doc=>`${doc.kind}: ${doc.original_name}`).join(", ")||"Aucun"]]};}
async function recruiterSummary(env,id){const row=await env.DB.prepare("SELECT u.id,u.email,u.created_at,p.* FROM users u JOIN recruiter_profiles p ON p.user_id=u.id WHERE u.id=?").bind(id).first();if(!row)return null;const answers=parse(row.questionnaire_answers,{});return{kind:"recruiter",name:`${row.first_name} ${row.last_name}`,fields:[["Date",row.created_at],["ID utilisateur",row.id],["Nom",row.last_name],["Prénom",row.first_name],["Email",row.email],["Téléphone",row.phone],["Fonction",row.job_title],["Entreprise",row.company_name],["Secteur",row.company_sector],["Taille",row.company_size],["Ville",row.city],["Site",row.website],["Profils recherchés",answers.recruitmentDomains],["Recrutements prévus",answers.plannedHires],["Échéance",answers.hiringDelay]]};}
async function genericSummary(env,type,id){if(type==="new_job"){const row=await env.DB.prepare("SELECT j.id,j.created_at,j.title,j.domain,j.contract_type,j.city,j.work_mode,j.status,c.name company FROM job_offers j LEFT JOIN companies c ON c.id=j.company_id WHERE j.id=?").bind(id).first();return row&&{kind:"job",name:row.title,fields:Object.entries(row)};}if(type==="new_application"){const row=await env.DB.prepare("SELECT a.id,a.created_at,a.status,j.title,cp.first_name,cp.last_name,u.email,c.name company FROM applications a JOIN job_offers j ON j.id=a.job_offer_id JOIN users u ON u.id=a.candidate_user_id JOIN candidate_profiles cp ON cp.user_id=u.id LEFT JOIN companies c ON c.id=j.company_id WHERE a.id=?").bind(id).first();return row&&{kind:"application",name:`${row.first_name} ${row.last_name}`,fields:Object.entries(row)};}return{kind:type,name:"Workcrute",fields:[["Date",new Date().toISOString()],["Type",type],["Ressource",id||"-"]]};}
async function summaryFor(env,type,id){if(type==="new_candidate")return candidateSummary(env,id);if(type==="new_recruiter")return recruiterSummary(env,id);return genericSummary(env,type,id);}
const settingColumn={new_candidate:"email_new_candidate",new_recruiter:"email_new_recruiter",new_job:"email_new_job",new_application:"email_new_application",critical_error:"email_critical_error",suspicious_admin_login:"email_suspicious_admin_login"};
export async function enqueueAdminEmail(env,eventType,resourceType,resourceId,{delaySeconds=0,recipient=null}={}){const config=await env.DB.prepare("SELECT * FROM admin_security_config WHERE id=1").first();if(eventType!=="test"&&(!config?.primary_email_verified_at||!config?.[settingColumn[eventType]]))return null;if(!recipient&&!config?.primary_email)return null;const id=crypto.randomUUID(),due=new Date(Date.now()+delaySeconds*1000).toISOString().slice(0,19).replace("T"," ");const result=await env.DB.prepare("INSERT OR IGNORE INTO admin_email_outbox(id,event_type,resource_type,resource_id,recipient,next_attempt_at) VALUES(?,?,?,?,?,?)").bind(id,eventType,resourceType||null,resourceId||null,recipient||config.primary_email,due).run();return result.meta?.changes?id:null;}
async function addAdminNotice(env,title,body,severity="warning"){await env.DB.prepare("INSERT INTO admin_notifications(id,category,title,body,severity,href) VALUES(?,?,?,?,?,?)").bind(crypto.randomUUID(),"email",title,body,severity,"/admin/parametres/").run();}
const subjectFor=(type,summary)=>type==="new_candidate"?`[Workcrute] Nouveau compte candidat — ${summary.name}`:type==="new_recruiter"?`[Workcrute] Nouveau compte recruteur — ${summary.name}`:type==="new_job"?`[Workcrute] Nouvelle offre — ${summary.name}`:type==="new_application"?`[Workcrute] Nouvelle candidature — ${summary.name}`:type==="critical_error"?"[Workcrute] Erreur critique":type==="suspicious_admin_login"?"[Workcrute] Connexion admin suspecte":"[Workcrute] Email administratif de test";
async function deliver(env,row){const config=await env.DB.prepare("SELECT * FROM admin_security_config WHERE id=1").first(),summary=await summaryFor(env,row.event_type,row.resource_id),subject=subjectFor(row.event_type,summary),attachments=[],mode=row.event_type==="test"?"none":config.email_attachment_mode;if(["pdf","both"].includes(mode)){const bytes=createSummaryPdf(summary);attachments.push({content:bytesToBase64(bytes),filename:`workcrute-${summary.kind}-${row.resource_id||"test"}.pdf`,type:"application/pdf",disposition:"attachment"});}if(["csv","both"].includes(mode)){attachments.push({content:bytesToBase64(ascii(createSummaryCsv(summary))),filename:`workcrute-${summary.kind}-${row.resource_id||"test"}.csv`,type:"text/csv; charset=utf-8",disposition:"attachment"});}const html=`<div style="font-family:Arial,sans-serif;color:#142033"><div style="background:#10233f;color:white;padding:24px"><h1 style="margin:0">Workcrute</h1><p style="margin:6px 0 0">Notification administrative</p></div><div style="padding:24px"><h2>${htmlEscape(subject)}</h2><table style="border-collapse:collapse;width:100%">${summary.fields.map(([label,value])=>`<tr><th style="text-align:left;padding:8px;border-bottom:1px solid #dfe7f1">${htmlEscape(label)}</th><td style="padding:8px;border-bottom:1px solid #dfe7f1">${htmlEscape(value)}</td></tr>`).join("")}</table><p style="color:#64748b">Cet email ne contient aucun mot de passe, token, session, OTP ou secret.</p></div></div>`,text=`${subject}\n\n${summary.fields.map(([label,value])=>`${label}: ${safeText(value)}`).join("\n")}\n\nAucun secret n’est inclus.`;let providerId=null;if(env.ENVIRONMENT==="test"){providerId="test-delivery";}else if(env.EMAIL?.send){const sent=await env.EMAIL.send({to:row.recipient,from:env.EMAIL_FROM,subject,html,text,attachments});providerId=sent?.id||null;}else if(env.EMAIL_PROVIDER_API_KEY&&env.EMAIL_FROM){const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${env.EMAIL_PROVIDER_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({from:env.EMAIL_FROM,to:[row.recipient],subject,html,text,attachments})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`EMAIL_PROVIDER_${response.status}`);providerId=result.id||null;}else throw new Error("EMAIL_PROVIDER_NOT_CONFIGURED");return{subject,summary,attachments,providerId};}
export async function processAdminEmailOutbox(env,limit=10){const {results=[]}=await env.DB.prepare("SELECT * FROM admin_email_outbox WHERE status IN ('pending','failed') AND attempts<max_attempts AND next_attempt_at<=CURRENT_TIMESTAMP ORDER BY created_at LIMIT ?").bind(limit).all();const report={sent:0,failed:0};for(const row of results){await env.DB.prepare("UPDATE admin_email_outbox SET status='processing',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(row.id).run();try{const result=await deliver(env,row);await env.DB.batch([env.DB.prepare("UPDATE admin_email_outbox SET status='sent',attempts=attempts+1,last_error=NULL,sent_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(row.id),env.DB.prepare("INSERT INTO admin_email_delivery_logs(id,outbox_id,recipient,event_type,subject,attachment_names_json,body_snapshot_json,success,provider_message_id) VALUES(?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),row.id,row.recipient,row.event_type,result.subject,JSON.stringify(result.attachments.map(a=>a.filename)),JSON.stringify({fields:result.summary.fields}),1,result.providerId)]);report.sent++;}catch(error){const attempts=Number(row.attempts)+1,terminal=attempts>=Number(row.max_attempts),delay=Math.min(3600,60*2**Math.max(0,attempts-1)),message=String(error?.message||error).slice(0,500);await env.DB.batch([env.DB.prepare("UPDATE admin_email_outbox SET status='failed',attempts=?,last_error=?,next_attempt_at=datetime('now',?),updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(attempts,message,`+${delay} seconds`,row.id),env.DB.prepare("INSERT INTO admin_email_delivery_logs(id,outbox_id,recipient,event_type,subject,success,error_message) VALUES(?,?,?,?,?,0,?)").bind(crypto.randomUUID(),row.id,row.recipient,row.event_type,"Échec email administratif",message)]);try{await recordAppError(env,{requestId:`email-${row.id}`,severity:terminal?"critical":"error",service:"email",code:"EMAIL_DELIVERY_ERROR",userMessage:"Un email administratif n’a pas pu être envoyé.",technicalMessage:message,route:"admin-email-outbox",method:"SCHEDULED",httpStatus:503,metadata:{eventType:row.event_type,attempts}});}catch{}await addAdminNotice(env,terminal?"Email administratif abandonné":"Échec email administratif",terminal?`L’email ${row.event_type} a échoué après ${attempts} tentatives.`:`Une nouvelle tentative de l’email ${row.event_type} est planifiée.`,terminal?"critical":"warning");report.failed++;}}return report;}
