const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8",...headers}});
const bad=(message,status=400)=>json({error:message},status);
const textEncoder=new TextEncoder();
const allowedFiles=new Map([["application/pdf","pdf"],["application/msword","doc"],["application/vnd.openxmlformats-officedocument.wordprocessingml.document","docx"]]);
const maxFileBytes=8*1024*1024;
const cors=(request)=>({"access-control-allow-origin":new URL(request.url).origin,"access-control-allow-credentials":"true","access-control-allow-headers":"content-type, x-turnstile-token","access-control-allow-methods":"GET,POST,PATCH,DELETE,OPTIONS"});
function now(){return new Date().toISOString()}
function future(days){return new Date(Date.now()+days*86400000).toISOString()}
function safeString(value,max=500){return typeof value==="string"&&value.trim().length<=max?value.trim():""}
function validPhone(phone){return /^\+212[5-7]\d{8}$/.test(phone.replace(/[\s.-]/g,""))}
function validPassword(password){return typeof password==="string"&&password.length>=12&&/[a-z]/.test(password)&&/[A-Z]/.test(password)&&/\d/.test(password)}
function randomToken(){const bytes=crypto.getRandomValues(new Uint8Array(32));return btoa(String.fromCharCode(...bytes)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
async function digest(value){const bytes=await crypto.subtle.digest("SHA-256",textEncoder.encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function passwordHash(password,salt){const key=await crypto.subtle.importKey("raw",textEncoder.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:textEncoder.encode(salt),iterations:310000,hash:"SHA-256"},key,256);return btoa(String.fromCharCode(...new Uint8Array(bits)))}
function cookie(name,value,maxAge=0){return name+"="+value+"; Path=/; HttpOnly; Secure; SameSite=Lax"+(maxAge?"; Max-Age="+maxAge:"; Max-Age=0")}
function sessionToken(request){const match=request.headers.get("cookie")?.match(/(?:^|;\s*)wc_session=([^;]+)/);return match?.[1]||null}
async function userFor(request,env){const token=sessionToken(request);if(!token)return null;const hash=await digest(token+env.SESSION_PEPPER);const row=await env.DB.prepare("SELECT u.id,u.email,u.role,u.email_verified_at,s.id AS session_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?").bind(hash,now()).first();return row||null}
async function requireUser(request,env){const user=await userFor(request,env);if(!user)throw new Response(JSON.stringify({error:"Authentification requise"}),{status:401,headers:{"content-type":"application/json"}});return user}
async function createSession(env,userId){const raw=randomToken(),id=crypto.randomUUID(),hash=await digest(raw+env.SESSION_PEPPER);await env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,?)").bind(id,userId,hash,future(30)).run();return raw}
async function profile(env,user){if(user.role==="candidate")return env.DB.prepare("SELECT first_name,last_name,phone,city,region,preferred_language,professional_title,introduction,availability,questionnaire_answers FROM candidate_profiles WHERE user_id=?").bind(user.id).first();if(user.role==="recruiter")return env.DB.prepare("SELECT first_name,last_name,phone,company_name,job_title FROM recruiter_profiles WHERE user_id=?").bind(user.id).first();return null}
async function emailToken(env,userId,purpose){const raw=randomToken(),hash=await digest(raw+env.SESSION_PEPPER);await env.DB.prepare("INSERT INTO email_tokens(id,user_id,token_hash,purpose,expires_at) VALUES(?,?,?,?,?)").bind(crypto.randomUUID(),userId,hash,purpose,future(1)).run();return raw}
async function sendEmail(env,message){if(!env.EMAIL_PROVIDER_API_KEY||!env.EMAIL_FROM)return;console.log(JSON.stringify({event:"email_queued",to:message.to,template:message.template}));}
async function register(request,env){const body=await request.json().catch(()=>null);if(!body)return bad("Données invalides");const role=body.role==="recruiter"?"recruiter":"candidate",email=safeString(body.email,254).toLowerCase(),first=safeString(body.firstName,80),last=safeString(body.lastName,80),phone=safeString(body.phone,20).replace(/[\s.-]/g,""),password=body.password;if(!first||!last||!/^\S+@\S+\.\S+$/.test(email)||!validPhone(phone)||!validPassword(password)||body.acceptedTerms!==true)return bad("Veuillez vérifier les informations du formulaire.");if(body.password!==body.confirmPassword)return bad("Les mots de passe ne correspondent pas.");const exists=await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first();if(exists)return bad("Impossible de créer ce compte avec ces informations.",409);const id=crypto.randomUUID(),salt=randomToken(),hash=await passwordHash(password,salt);await env.DB.batch([env.DB.prepare("INSERT INTO users(id,email,password_hash,password_salt,role) VALUES(?,?,?,?,?)").bind(id,email,hash,salt,role),role==="candidate"?env.DB.prepare("INSERT INTO candidate_profiles(user_id,first_name,last_name,phone,preferred_language) VALUES(?,?,?,?,?)").bind(id,first,last,phone,body.language||"fr"):env.DB.prepare("INSERT INTO recruiter_profiles(user_id,first_name,last_name,phone,company_name,job_title) VALUES(?,?,?,?,?,?)").bind(id,first,last,phone,safeString(body.companyName,120)||null,safeString(body.jobTitle,120)||null),env.DB.prepare("INSERT INTO notifications(id,user_id,type,title,body) VALUES(?,?,?,?,?)").bind(crypto.randomUUID(),id,"account","Bienvenue sur Workcrute","Complétez votre profil pour améliorer vos opportunités.")]);const verify=await emailToken(env,id,"verify_email");await sendEmail(env,{to:email,template:"verify_email",token:verify});const session=await createSession(env,id);return json({user:{id,email,role},emailVerificationPending:true},{status:201,headers:{"set-cookie":cookie("wc_session",session,2592000)}})}
async function login(request,env){const body=await request.json().catch(()=>null),email=safeString(body?.email,254).toLowerCase(),password=body?.password;if(!email||typeof password!=="string")return bad("Identifiants invalides.",401);const user=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(email).first();if(!user)return bad("Identifiants invalides.",401);const hash=await passwordHash(password,user.password_salt);if(!crypto.subtle.timingSafeEqual(textEncoder.encode(hash),textEncoder.encode(user.password_hash)))return bad("Identifiants invalides.",401);const session=await createSession(env,user.id);return json({user:{id:user.id,email:user.email,role:user.role},emailVerificationPending:!user.email_verified_at},200,{"set-cookie":cookie("wc_session",session,2592000)})}
async function questionnaire(env){const {results=[]}=await env.DB.prepare("SELECT id,field_key,type,labels_json,description_json,options_json,sort_order,is_required FROM questionnaire_questions WHERE is_active=1 ORDER BY sort_order").all();return json(results.map(q=>({...q,labels:JSON.parse(q.labels_json),description:q.description_json?JSON.parse(q.description_json):null,options:q.options_json?JSON.parse(q.options_json):[]})))}
async function getProfile(request,env){const user=await requireUser(request,env);return json({user:{id:user.id,email:user.email,role:user.role,emailVerified:Boolean(user.email_verified_at)},profile:await profile(env,user)})}
async function patchProfile(request,env){const user=await requireUser(request,env),body=await request.json().catch(()=>null);if(!body)return bad("Données invalides");if(user.role!=="candidate")return bad("Profil candidat requis.",403);const intro=safeString(body.introduction,1000),title=safeString(body.professionalTitle,120),city=safeString(body.city,120),region=safeString(body.region,120),availability=safeString(body.availability,80),language=["fr","ar","en","tzm"].includes(body.language)?body.language:"fr",answers=body.questionnaireAnswers&&typeof body.questionnaireAnswers==="object"?JSON.stringify(body.questionnaireAnswers):"{}";await env.DB.prepare("UPDATE candidate_profiles SET city=?,region=?,preferred_language=?,professional_title=?,introduction=?,availability=?,questionnaire_answers=?,updated_at=CURRENT_TIMESTAMP WHERE user_id=?").bind(city||null,region||null,language,title||null,intro||null,availability||null,answers,user.id).run();return getProfile(request,env)}
async function documents(request,env){const user=await requireUser(request,env);if(request.method==="GET"){const {results=[]}=await env.DB.prepare("SELECT id,kind,original_name,content_type,size_bytes,is_default,created_at FROM documents WHERE user_id=? AND deleted_at IS NULL ORDER BY created_at DESC").bind(user.id).all();return json(results)}if(request.method==="POST"){const form=await request.formData(),file=form.get("file"),kind=form.get("kind");if(!(file instanceof File)||!["cv","cover_letter"].includes(kind))return bad("Document invalide.");const ext=allowedFiles.get(file.type);if(!ext||file.size===0||file.size>maxFileBytes||!file.name.toLowerCase().endsWith("."+ext))return bad("Le document doit être un PDF, DOC ou DOCX de moins de 8 Mo.");const id=crypto.randomUUID(),key="private/"+user.id+"/"+id+"."+ext;await env.DOCUMENTS.put(key,file.stream(),{httpMetadata:{contentType:file.type},customMetadata:{owner:user.id,kind}});const count=await env.DB.prepare("SELECT COUNT(*) AS total FROM documents WHERE user_id=? AND kind=? AND deleted_at IS NULL").bind(user.id,kind).first();await env.DB.prepare("INSERT INTO documents(id,user_id,kind,storage_key,original_name,content_type,size_bytes,is_default) VALUES(?,?,?,?,?,?,?,?)").bind(id,user.id,kind,key,file.name,file.type,file.size,count.total===0?1:0).run();return json({id,kind,name:file.name},201)}const id=new URL(request.url).pathname.split("/").pop(),doc=await env.DB.prepare("SELECT storage_key FROM documents WHERE id=? AND user_id=? AND deleted_at IS NULL").bind(id,user.id).first();if(!doc)return bad("Document introuvable.",404);await env.DOCUMENTS.delete(doc.storage_key);await env.DB.prepare("UPDATE documents SET deleted_at=CURRENT_TIMESTAMP,is_default=0 WHERE id=?").bind(id).run();return new Response(null,{status:204})}
async function notifications(request,env){const user=await requireUser(request,env);if(request.method==="POST"){await env.DB.prepare("UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE user_id=? AND read_at IS NULL").bind(user.id).run();return new Response(null,{status:204})}const {results=[]}=await env.DB.prepare("SELECT id,type,title,body,href,read_at,created_at FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50").bind(user.id).all();return json(results)}
async function authAction(request,env,purpose){const body=await request.json().catch(()=>({})),email=safeString(body.email,254).toLowerCase();if(!email)return json({ok:true});const user=await env.DB.prepare("SELECT id,email FROM users WHERE email=?").bind(email).first();if(user){const token=await emailToken(env,user.id,purpose);await sendEmail(env,{to:user.email,template:purpose,token});}return json({ok:true})}
export default {async fetch(request,env,ctx){const url=new URL(request.url),path=url.pathname;if(request.method==="OPTIONS")return new Response(null,{headers:cors(request)});try{let response;if(path==="/api/auth/register"&&request.method==="POST")response=await register(request,env);else if(path==="/api/auth/login"&&request.method==="POST")response=await login(request,env);else if(path==="/api/auth/logout"&&request.method==="POST"){const token=sessionToken(request);if(token)await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await digest(token+env.SESSION_PEPPER)).run();response=json({ok:true},200,{"set-cookie":cookie("wc_session","")})}else if(path==="/api/auth/me")response=await getProfile(request,env);else if(path==="/api/auth/forgot-password"&&request.method==="POST")response=await authAction(request,env,"reset_password");else if(path==="/api/auth/resend-verification"&&request.method==="POST")response=await authAction(request,env,"verify_email");else if(path==="/api/questionnaire")response=await questionnaire(env);else if(path==="/api/profile"&&request.method==="PATCH")response=await patchProfile(request,env);else if(path==="/api/documents"||path.startsWith("/api/documents/"))response=await documents(request,env);else if(path==="/api/notifications")response=await notifications(request,env);else response=await env.ASSETS.fetch(request);const headers=new Headers(response.headers);Object.entries(cors(request)).forEach(([k,v])=>headers.set(k,v));return new Response(response.body,{status:response.status,headers})}catch(error){if(error instanceof Response)return error;console.error(JSON.stringify({event:"api_error",path,error:String(error)}));return bad("Une erreur est survenue.",500)}}};