import { requireV2Session } from './v2-auth.js';
import { renderBillingPdf } from './billing-pdf.js';
import { sendTransactionalEmail } from './email-provider.js';

const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const fail=(code,status=422)=>{throw json({code,userMessage:code},status);};
const fields=['legal_name','address','cnif','ice','fiscal_id','professional_tax','phone','email','signature'];
const clean=(value,max=160)=>typeof value==='string'&&value.trim().length<=max?value.trim():'';
const email=value=>/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(value)&&value.length<=254;
const uuid=()=>crypto.randomUUID();
const parse=value=>JSON.parse(value||'{}');
const currentDate=(now=new Date(),zone='Africa/Casablanca')=>new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(now);
const currentPeriod=()=>currentDate().slice(0,7);
const history=(env,id,account,actor,event,details={},claim=null)=>env.DB.prepare(`INSERT INTO v2_billing_history(id,invoice_id,employee_account_id,actor_id,event,details_json) SELECT ?,?,?,?,?,? ${claim?'WHERE EXISTS(SELECT 1 FROM v2_billing_invoices WHERE id=? AND last_transition_id=?)':''}`).bind(uuid(),id,account,actor,event,JSON.stringify(details),...(claim?[id,claim]:[]));
const profile=async(env,account)=>env.DB.prepare('SELECT legal_name,address,cnif,ice,fiscal_id,professional_tax,phone,email,signature,updated_at FROM v2_billing_profiles WHERE account_id=?').bind(account).first();
const config=env=>env.DB.prepare('SELECT * FROM v2_billing_config WHERE id=1').first();
async function adminRecipient(env,cfg){return cfg.admin_email||(await env.DB.prepare('SELECT primary_email FROM admin_security_config WHERE id=1 AND primary_email_verified_at IS NOT NULL').first())?.primary_email||'';}

export function amountInCentimes(value){const raw=String(value??'0').trim().replace(',','.');if(!/^\d{1,7}(\.\d{1,2})?$/.test(raw))return null;const [whole,fraction='']=raw.split('.');return Number(whole)*100+Number(fraction.padEnd(2,'0'));}
function amounts(body){const result={},details={};for(const key of ['service','expenses','bonus','other']){const amount=amountInCentimes(body[key]);if(amount===null)fail('BILLING_AMOUNT_INVALID');result[key+'_centimes']=amount;const detail=body.details?.[key];if(detail!==undefined&&(typeof detail!=='string'||detail.trim().length>80))fail('BILLING_DETAILS_INVALID');details[key]=clean(detail,80);}if(result.other_centimes&&!details.other)fail('BILLING_OTHER_REQUIRED');result.total_centimes=Object.values(result).reduce((sum,n)=>sum+n,0);if(result.total_centimes>999999999)fail('BILLING_AMOUNT_INVALID');return{...result,details_json:JSON.stringify(details)};}
function validPeriod(value){return /^\d{4}-(0[1-9]|1[0-2])$/.test(value)&&value>='2000-01'&&value<=currentPeriod();}
async function rowFor(env,id,account){const row=await env.DB.prepare(`SELECT * FROM v2_billing_invoices WHERE id=? ${account?'AND employee_account_id=?':''}`).bind(id,...(account?[account]:[])).first();if(!row)fail('BILLING_NOT_FOUND',404);return row;}
async function detail(env,row){const [events,versions]=await Promise.all([env.DB.prepare('SELECT event,actor_id,details_json,created_at FROM v2_billing_history WHERE invoice_id IN (SELECT id FROM v2_billing_invoices WHERE employee_account_id=? AND period=?) ORDER BY created_at,id').bind(row.employee_account_id,row.period).all(),env.DB.prepare('SELECT id,version,status,reference,created_at FROM v2_billing_invoices WHERE employee_account_id=? AND period=? ORDER BY version').bind(row.employee_account_id,row.period).all()]);return json({item:row,history:events.results||[],versions:versions.results||[]});}

async function saveProfile(request,env,account){const body=await request.json().catch(()=>({})),value={};for(const key of fields){value[key]=clean(body[key],key==='address'?320:key==='email'?254:160);if(key!=='signature'&&!value[key])fail('BILLING_PROFILE_INCOMPLETE');}if(!email(value.email)||!/^\+?[0-9 ()-]{8,30}$/.test(value.phone))fail('BILLING_CONTACT_INVALID');const before=await profile(env,account);await env.DB.batch([env.DB.prepare(`INSERT INTO v2_billing_profiles(account_id,${fields.join(',')}) VALUES(${['account_id',...fields].map(()=>'?').join(',')}) ON CONFLICT(account_id) DO UPDATE SET ${fields.map(key=>key+'=excluded.'+key).join(',')},updated_at=CURRENT_TIMESTAMP`).bind(account,...fields.map(key=>value[key])),history(env,null,account,account,'profile_saved',{before,after:value})]);return json({profile:await profile(env,account)});}

async function create(request,env,session,previous){const body=await request.json().catch(()=>({})),period=previous?.period||body.period;if(!validPeriod(period))fail('BILLING_PERIOD_INVALID');const account=await env.DB.prepare('SELECT COALESCE(NULLIF(p.hire_date,\'\'),a.created_at) started FROM v2_accounts a JOIN v2_employee_profiles p ON p.account_id=a.id WHERE a.id=?').bind(session.account_id).first();if(period<String(account.started).slice(0,7))fail('BILLING_PERIOD_INVALID');const existing=await env.DB.prepare("SELECT * FROM v2_billing_invoices WHERE employee_account_id=? AND period=? AND status IN ('draft','submitted','approved','paid')").bind(session.account_id,period).first();if(existing){if(existing.status==='draft')return detail(env,existing);fail('BILLING_MONTH_EXISTS',409);}const latest=await env.DB.prepare('SELECT * FROM v2_billing_invoices WHERE employee_account_id=? AND period=? ORDER BY version DESC LIMIT 1').bind(session.account_id,period).first();const id=uuid(),version=(latest?.version||0)+1,p=previous||latest,values=previous?{service_centimes:p.service_centimes,expenses_centimes:p.expenses_centimes,bonus_centimes:p.bonus_centimes,other_centimes:p.other_centimes,total_centimes:p.total_centimes,details_json:p.details_json}:amounts(body);try{await env.DB.batch([env.DB.prepare('INSERT INTO v2_billing_invoices(id,employee_account_id,period,version,previous_id,service_centimes,expenses_centimes,bonus_centimes,other_centimes,total_centimes,details_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(id,session.account_id,period,version,p?.id||null,values.service_centimes,values.expenses_centimes,values.bonus_centimes,values.other_centimes,values.total_centimes,values.details_json),history(env,id,session.account_id,session.account_id,'created',{period,version,previous_id:p?.id||null})]);}catch(error){if(String(error).includes('UNIQUE'))fail('BILLING_MONTH_EXISTS',409);throw error;}return detail(env,await rowFor(env,id,session.account_id));}

async function edit(request,env,row,actor,remove=false){const body=await request.json().catch(()=>({}));if(row.status!=='draft')fail('BILLING_LOCKED',409);if(body.revision!==row.revision)fail('BILLING_STALE',409);const claim=uuid(),values=remove?row:amounts(body);await env.DB.batch([env.DB.prepare("UPDATE v2_billing_invoices SET service_centimes=?,expenses_centimes=?,bonus_centimes=?,other_centimes=?,total_centimes=?,details_json=?,status=?,revision=revision+1,last_transition_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='draft' AND revision=?").bind(values.service_centimes,values.expenses_centimes,values.bonus_centimes,values.other_centimes,values.total_centimes,values.details_json,remove?'deleted':'draft',claim,row.id,row.revision),history(env,row.id,row.employee_account_id,actor,remove?'deleted':'updated',{before:{service:row.service_centimes,expenses:row.expenses_centimes,bonus:row.bonus_centimes,other:row.other_centimes},after:values},claim)]);const updated=await rowFor(env,row.id,row.employee_account_id);if(updated.last_transition_id!==claim)fail('BILLING_STALE',409);return detail(env,updated);}

function queueStatement(env,{claim,row,event,recipient,language='fr'}){return env.DB.prepare('INSERT OR IGNORE INTO v2_billing_email_outbox(id,dedupe_key,invoice_id,employee_account_id,period,event,recipient,language) SELECT ?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM v2_billing_invoices WHERE id=? AND last_transition_id=?)').bind(uuid(),`${row.id}:${event}`,row.id,row.employee_account_id,row.period,event,recipient,language,row.id,claim);}
async function submit(request,env,row,session){if(row.status==='submitted')return detail(env,row);if(row.status!=='draft')fail('BILLING_LOCKED',409);const body=await request.json().catch(()=>({}));if(body.revision!==row.revision)fail('BILLING_STALE',409);if(row.total_centimes<=0)fail('BILLING_TOTAL_REQUIRED');const issuer=await profile(env,row.employee_account_id);if(!issuer)fail('BILLING_PROFILE_INCOMPLETE');const cfg=await config(env),recipient=await adminRecipient(env,cfg);if(!cfg.client_address||!recipient)fail('BILLING_CONFIG_INCOMPLETE');const claim=uuid(),client={client_name:cfg.client_name,client_address:cfg.client_address,tax_mention:cfg.tax_mention},bytes=await renderBillingPdf({...row,submitted_at:new Date().toISOString().slice(0,19).replace('T',' ')},issuer,client,false);await env.DB.batch([
  env.DB.prepare("UPDATE v2_billing_invoices SET status='submitted',issuer_json=?,client_json=?,submitted_at=CURRENT_TIMESTAMP,last_transition_id=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='draft' AND revision=?").bind(JSON.stringify(issuer),JSON.stringify(client),claim,row.id,row.revision),
  env.DB.prepare('INSERT INTO v2_billing_documents(invoice_id,kind,data) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM v2_billing_invoices WHERE id=? AND last_transition_id=?)').bind(row.id,'preview',bytes,row.id,claim),
  history(env,row.id,row.employee_account_id,session.account_id,'submitted',{issuer,client,total_centimes:row.total_centimes},claim),
  env.DB.prepare("INSERT INTO admin_notifications(id,category,title,body,severity,href) SELECT ?,'invoices','Facture mensuelle soumise',?,'info',? WHERE EXISTS(SELECT 1 FROM v2_billing_invoices WHERE id=? AND last_transition_id=?)").bind(uuid(),`${session.first_name} ${session.last_name} - ${row.period}`,`/admin/factures/?id=${row.id}`,row.id,claim),
  queueStatement(env,{claim,row,event:'submitted',recipient})
]);const updated=await rowFor(env,row.id);if(updated.last_transition_id!==claim)fail('BILLING_STALE',409);return detail(env,updated);}

async function ensureOfficialPdf(env,row){let doc=await env.DB.prepare("SELECT data FROM v2_billing_documents WHERE invoice_id=? AND kind='official'").bind(row.id).first();if(!doc){const bytes=await renderBillingPdf(row,parse(row.issuer_json),parse(row.client_json),true);await env.DB.prepare("INSERT OR IGNORE INTO v2_billing_documents(invoice_id,kind,data) VALUES(?,'official',?)").bind(row.id,bytes).run();doc=await env.DB.prepare("SELECT data FROM v2_billing_documents WHERE invoice_id=? AND kind='official'").bind(row.id).first();}return new Uint8Array(doc.data);}
async function pdfResponse(env,row){let data;if(row.reference)data=await ensureOfficialPdf(env,row);else if(row.status==='draft'){const issuer=await profile(env,row.employee_account_id);if(!issuer)fail('BILLING_PROFILE_INCOMPLETE');data=await renderBillingPdf(row,issuer,await config(env),false);}else{const doc=await env.DB.prepare("SELECT data FROM v2_billing_documents WHERE invoice_id=? AND kind='preview'").bind(row.id).first();if(!doc)fail('BILLING_NOT_FOUND',404);data=new Uint8Array(doc.data);}return new Response(data,{headers:{'content-type':'application/pdf','content-disposition':`inline; filename="facture-${row.reference||row.period+'-v'+row.version}.pdf"`,'cache-control':'no-store','x-content-type-options':'nosniff'}});}

async function decision(request,env,row,action,actor){const body=await request.json().catch(()=>({})),status={approve:'approved',refuse:'refused',pay:'paid',cancel:'cancelled'}[action];if(!status)fail('BILLING_ACTION_INVALID',405);if(row.status===status)return detail(env,row);if((['approve','refuse'].includes(action)&&row.status!=='submitted')||(action==='pay'&&row.status!=='approved')||(action==='cancel'&&!['submitted','approved'].includes(row.status)))fail('BILLING_LOCKED',409);if(body.revision!==row.revision)fail('BILLING_STALE',409);const note=clean(body.note,1000),payment=clean(body.paymentReference,120);if(['refuse','cancel'].includes(action)&&!note)fail('BILLING_NOTE_REQUIRED');if(action==='pay'&&((!/^\d{4}-\d{2}-\d{2}$/.test(body.paidAt||'')||!Number.isFinite(Date.parse(body.paidAt))||new Date(body.paidAt).toISOString().slice(0,10)!==body.paidAt)||!payment))fail('BILLING_PAYMENT_REQUIRED');const claim=uuid(),statements=[env.DB.prepare('UPDATE v2_billing_invoices SET status=?,admin_note=?,payment_reference=?,paid_at=?,approved_at=CASE WHEN ?=\'approved\' THEN CURRENT_TIMESTAMP ELSE approved_at END,revision=revision+1,last_transition_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status=? AND revision=?').bind(status,note||null,payment||row.payment_reference||null,action==='pay'?body.paidAt:row.paid_at,status,claim,row.id,row.status,row.revision)];if(action==='approve'){statements.push(env.DB.prepare('INSERT INTO v2_billing_sequence(invoice_id) SELECT ? WHERE EXISTS(SELECT 1 FROM v2_billing_invoices WHERE id=? AND last_transition_id=?)').bind(row.id,row.id,claim),env.DB.prepare("UPDATE v2_billing_invoices SET reference=printf('%06d',(SELECT id FROM v2_billing_sequence WHERE invoice_id=?)) WHERE id=? AND last_transition_id=?").bind(row.id,row.id,claim));}statements.push(history(env,row.id,row.employee_account_id,actor,status,{note,payment_reference:payment,paid_at:body.paidAt||null},claim),env.DB.prepare('INSERT INTO v2_billing_notifications(id,employee_account_id,period,event,invoice_id) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM v2_billing_invoices WHERE id=? AND last_transition_id=?)').bind(uuid(),row.employee_account_id,row.period,status,row.id,row.id,claim));const issuer=parse(row.issuer_json),language=(await env.DB.prepare('SELECT preferred_language FROM v2_accounts WHERE id=?').bind(row.employee_account_id).first()).preferred_language;statements.push(queueStatement(env,{claim,row,event:status,recipient:issuer.email,language}));if(action==='approve'){const cfg=await config(env),recipient=await adminRecipient(env,cfg);if(recipient)statements.push(queueStatement(env,{claim,row,event:'issued',recipient}));}await env.DB.batch(statements);const updated=await rowFor(env,row.id);if(updated.last_transition_id!==claim)fail('BILLING_STALE',409);if(action==='approve')await ensureOfficialPdf(env,updated);return detail(env,updated);}

export async function billingApi(request,env,path,adminSession=null){const admin=path.startsWith('/api/admin/'),base=admin?'/api/admin/v2/billing':'/api/v2/employee/billing';if(admin&&!adminSession)fail('BILLING_FORBIDDEN',403);const session=admin?null:await requireV2Session(request,env,['employee']),account=session?.account_id,actor=account||'admin:'+adminSession.id,suffix=path.slice(base.length);
  const origin=request.headers.get('origin');
  if(!['GET','HEAD'].includes(request.method)&&origin&&origin!==new URL(request.url).origin&&origin!==env.APP_ORIGIN)fail('BILLING_FORBIDDEN',403);
  if(!admin&&suffix==='/profile'){if(request.method==='GET')return json({profile:await profile(env,account)});if(request.method==='PUT')return saveProfile(request,env,account);if(request.method==='DELETE'){const before=await profile(env,account);await env.DB.batch([env.DB.prepare('DELETE FROM v2_billing_profiles WHERE account_id=?').bind(account),history(env,null,account,actor,'profile_deleted',{before})]);return json({ok:true});}}
  if(admin&&suffix==='/config'){if(request.method==='GET'){const cfg=await config(env);return json({config:{...cfg,admin_email:await adminRecipient(env,cfg)},emailConfigured:Boolean(env.EMAIL?.send||(env.EMAIL_FROM&&(env.BREVO_API_KEY||env.EMAIL_PROVIDER_API_KEY)))});}if(request.method==='PUT'){const body=await request.json().catch(()=>({})),name=clean(body.client_name,160),address=clean(body.client_address,320),recipient=clean(body.admin_email,254),mention=clean(body.tax_mention,160);if(!name||!address||!email(recipient))fail('BILLING_CONFIG_INCOMPLETE');await env.DB.prepare('UPDATE v2_billing_config SET client_name=?,client_address=?,tax_mention=?,admin_email=?,updated_at=CURRENT_TIMESTAMP WHERE id=1').bind(name,address,mention,recipient).run();return json({ok:true});}}
  if(admin&&suffix==='/emails'&&request.method==='GET')return json({items:(await env.DB.prepare('SELECT id,period,event,recipient,status,attempts,last_error,sent_at,created_at FROM v2_billing_email_outbox ORDER BY created_at DESC LIMIT 200').all()).results||[]});
  const retry=suffix.match(/^\/emails\/([^/]+)\/retry$/);if(admin&&retry&&request.method==='POST'){await env.DB.prepare("UPDATE v2_billing_email_outbox SET status='pending',attempts=0,next_attempt_at=CURRENT_TIMESTAMP,last_error=NULL WHERE id=? AND status='failed'").bind(retry[1]).run();return json({ok:true});}
  if(!admin&&suffix==='/notifications'){if(request.method==='GET')return json({items:(await env.DB.prepare('SELECT * FROM v2_billing_notifications WHERE employee_account_id=? ORDER BY created_at DESC LIMIT 100').bind(account).all()).results||[]});if(request.method==='PATCH'){const body=await request.json().catch(()=>({}));await env.DB.prepare('UPDATE v2_billing_notifications SET read_at=CURRENT_TIMESTAMP WHERE employee_account_id=? AND (? IS NULL OR id=?)').bind(account,body.id||null,body.id||null).run();return json({ok:true});}}
  if(suffix==='/invoices'){if(request.method==='GET'){const url=new URL(request.url),period=clean(url.searchParams.get('period'),7),status=clean(url.searchParams.get('status'),20),employee=admin?clean(url.searchParams.get('employee'),100):account;const where=["i.status<>'deleted'"],binds=[];if(employee){where.push('i.employee_account_id=?');binds.push(employee);}if(period){where.push('i.period=?');binds.push(period);}if(status){where.push('i.status=?');binds.push(status);}const items=(await env.DB.prepare(`SELECT i.*,a.first_name,a.last_name FROM v2_billing_invoices i JOIN v2_accounts a ON a.id=i.employee_account_id WHERE ${where.join(' AND ')} ORDER BY i.period DESC,i.version DESC LIMIT 500`).bind(...binds).all()).results||[];return json({items,currentPeriod:currentPeriod()});}if(!admin&&request.method==='POST')return create(request,env,session);}
  if(admin&&suffix==='/missing'&&request.method==='GET'){const period=new URL(request.url).searchParams.get('period')||currentPeriod();if(!validPeriod(period))fail('BILLING_PERIOD_INVALID');return json({period,items:(await env.DB.prepare("SELECT a.id,a.first_name,a.last_name,p.email,b.email billing_email,(SELECT status FROM v2_billing_invoices WHERE employee_account_id=a.id AND period=? ORDER BY version DESC LIMIT 1) invoice_status FROM v2_accounts a JOIN v2_employee_profiles p ON p.account_id=a.id LEFT JOIN v2_billing_profiles b ON b.account_id=a.id WHERE a.role='employee' AND a.account_status='active' AND substr(COALESCE(NULLIF(p.hire_date,\'\'),a.created_at),1,7)<=?").bind(period,period).all()).results||[]});}
  const match=suffix.match(/^\/invoices\/([^/]+)(?:\/(submit|recreate|pdf|approve|refuse|pay|cancel))?$/);if(match){const row=await rowFor(env,match[1],account),action=match[2];if(!action&&request.method==='GET')return detail(env,row);if(action==='pdf'&&request.method==='GET')return pdfResponse(env,row);if(!admin&&!action&&request.method==='PATCH')return edit(request,env,row,actor);if(!admin&&!action&&request.method==='DELETE')return edit(request,env,row,actor,true);if(!admin&&action==='submit'&&request.method==='POST')return submit(request,env,row,session);if(!admin&&action==='recreate'&&request.method==='POST'){if(!['refused','cancelled','deleted'].includes(row.status))fail('BILLING_LOCKED',409);return create(request,env,session,row);}if(admin&&request.method==='POST')return decision(request,env,row,action,actor);}
  fail('BILLING_ACTION_INVALID',405);
}

export function reminderDue(period,date){const next=new Date(period+'-01T00:00:00Z');next.setUTCMonth(next.getUTCMonth()+1);const day=new Date(date+'T00:00:00Z'),distance=Math.round((next-day)/86400000);return distance===7||(distance>=1&&distance<=4)||distance<=0;}
export async function generateBillingReminders(env,now=new Date()){const cfg=await config(env),date=currentDate(now,cfg.timezone),month=date.slice(0,7);let cursor='';let created=0;while(true){const employees=(await env.DB.prepare("SELECT a.id,a.preferred_language,a.created_at,p.hire_date,p.email fallback_email,b.email FROM v2_accounts a JOIN v2_employee_profiles p ON p.account_id=a.id LEFT JOIN v2_billing_profiles b ON b.account_id=a.id WHERE a.role='employee' AND a.account_status='active' AND a.id>? ORDER BY a.id LIMIT 100").bind(cursor).all()).results||[];if(!employees.length)break;for(const employee of employees){const hired=String(employee.hire_date||employee.created_at).slice(0,7),started=/^\d{4}-(0[1-9]|1[0-2])$/.test(hired)&&hired>cfg.reminders_start_period?hired:cfg.reminders_start_period;for(let period=started;period<=month;){if(reminderDue(period,date)){const existing=await env.DB.prepare('SELECT status FROM v2_billing_invoices WHERE employee_account_id=? AND period=? ORDER BY version DESC LIMIT 1').bind(employee.id,period).first();if(!['submitted','approved','paid'].includes(existing?.status)){const claim=uuid(),recipient=employee.email||employee.fallback_email||'',event=existing?.status==='refused'?'correction':'reminder';const statements=[env.DB.prepare('INSERT OR IGNORE INTO v2_billing_reminders(id,employee_account_id,period,reminder_date) VALUES(?,?,?,?)').bind(claim,employee.id,period,date),env.DB.prepare('INSERT INTO v2_billing_notifications(id,employee_account_id,period,event) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM v2_billing_reminders WHERE id=?)').bind(claim,employee.id,period,event,claim)];if(recipient)statements.push(env.DB.prepare('INSERT OR IGNORE INTO v2_billing_email_outbox(id,dedupe_key,employee_account_id,period,event,recipient,language) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM v2_billing_reminders WHERE id=?)').bind(uuid(),`${employee.id}:${period}:${date}`,employee.id,period,event,recipient,employee.preferred_language,claim));const results=await env.DB.batch(statements);created+=results[0].meta?.changes||0;}}const next=new Date(period+'-01T00:00:00Z');next.setUTCMonth(next.getUTCMonth()+1);period=next.toISOString().slice(0,7);}}cursor=employees.at(-1).id;}return{created};}

const copies={fr:{reminder:'Rappel de facture mensuelle',correction:'Facture à refaire',submitted:'Facture mensuelle soumise',approved:'Facture validée',issued:'Facture définitive disponible',refused:'Facture refusée',paid:'Facture payée',cancelled:'Facture annulée',body:'Consultez votre espace Workcrute pour la période'},en:{reminder:'Monthly invoice reminder',correction:'Invoice correction required',submitted:'Monthly invoice submitted',approved:'Invoice approved',issued:'Official invoice available',refused:'Invoice refused',paid:'Invoice paid',cancelled:'Invoice cancelled',body:'Open your Workcrute area for period'},ar:{reminder:'تذكير بالفاتورة الشهرية',correction:'يرجى إعادة الفاتورة',submitted:'تم إرسال الفاتورة الشهرية',approved:'تم قبول الفاتورة',issued:'الفاتورة النهائية متاحة',refused:'تم رفض الفاتورة',paid:'تم دفع الفاتورة',cancelled:'تم إلغاء الفاتورة',body:'راجع مساحة Workcrute للفترة'}};
const toBase64=bytes=>{let binary='';for(let n=0;n<bytes.length;n+=32768)binary+=String.fromCharCode(...bytes.subarray(n,n+32768));return btoa(binary);};
export async function processBillingEmails(env,limit=25){const rows=(await env.DB.prepare("SELECT * FROM v2_billing_email_outbox WHERE ((status IN ('pending','failed') AND next_attempt_at<=CURRENT_TIMESTAMP) OR (status='processing' AND lease_until<CURRENT_TIMESTAMP)) AND attempts<8 ORDER BY created_at LIMIT ?").bind(limit).all()).results||[];let sent=0,failed=0;for(const row of rows){const claimed=await env.DB.prepare("UPDATE v2_billing_email_outbox SET status='processing',lease_until=datetime('now','+5 minutes') WHERE id=? AND ((status IN ('pending','failed') AND next_attempt_at<=CURRENT_TIMESTAMP) OR (status='processing' AND lease_until<CURRENT_TIMESTAMP))").bind(row.id).run();if(!claimed.meta?.changes)continue;try{if(['reminder','correction'].includes(row.event)){const invoice=await env.DB.prepare('SELECT status FROM v2_billing_invoices WHERE employee_account_id=? AND period=? ORDER BY version DESC LIMIT 1').bind(row.employee_account_id,row.period).first();if(['submitted','approved','paid'].includes(invoice?.status)){await env.DB.prepare("UPDATE v2_billing_email_outbox SET status='sent',sent_at=CURRENT_TIMESTAMP,last_error='Reminder no longer needed' WHERE id=?").bind(row.id).run();continue;}}
      const copy=copies[row.language]||copies.fr,subject='[Workcrute] '+copy[row.event]+' - '+row.period,admin=['submitted','issued'].includes(row.event),url=(env.BILLING_APP_ORIGIN||'https://workcrute.aetbconseil.workers.dev')+(admin?'/admin/factures/':'/employe/factures/'),invoice=row.invoice_id?await rowFor(env,row.invoice_id):null,text=`${copy.body} ${row.period}.\n${url}${row.invoice_id?'?id='+row.invoice_id:''}${invoice?.admin_note?'\n'+invoice.admin_note:''}`,attachments=[];if(invoice&&['submitted','issued','approved'].includes(row.event)){const bytes=row.event==='submitted'?new Uint8Array((await env.DB.prepare("SELECT data FROM v2_billing_documents WHERE invoice_id=? AND kind='preview'").bind(invoice.id).first()).data):await ensureOfficialPdf(env,invoice);attachments.push({filename:`facture-${invoice.reference||invoice.period+'-v'+invoice.version}.pdf`,content:toBase64(bytes)});}if(env.ENVIRONMENT!=='test')await sendTransactionalEmail(env,{to:row.recipient,subject,text,attachments});await env.DB.prepare("UPDATE v2_billing_email_outbox SET status='sent',attempts=attempts+1,last_error=NULL,sent_at=CURRENT_TIMESTAMP,lease_until=NULL WHERE id=?").bind(row.id).run();sent++;}catch(error){await env.DB.prepare("UPDATE v2_billing_email_outbox SET status='failed',attempts=attempts+1,last_error=?,next_attempt_at=datetime('now',?),lease_until=NULL WHERE id=?").bind(String(error.message||error).slice(0,300),`+${Math.min(3600,60*2**row.attempts)} seconds`,row.id).run();failed++;}}return{sent,failed};}
export async function billingCycle(env){await generateBillingReminders(env);return processBillingEmails(env);}
