const entry = (id, category, questionFr, answerFr, questionEn, answerEn, questionAr, answerAr, keywords) => ({
  id: `v2-${id}`, category, question_fr: questionFr, answer_fr: answerFr,
  question_en: questionEn, answer_en: answerEn, question_ar: questionAr, answer_ar: answerAr,
  keywords_fr: keywords.fr, keywords_en: keywords.en, keywords_ar: keywords.ar,
  priority: 100, is_active: true,
});

export const V2_PUBLIC_FAQ = [
  entry("apply", "applications", "Comment envoyer ma candidature ?", "Déposez votre CV sur la page d’accueil, puis complétez les quatre étapes. Aucun compte candidat n’est nécessaire.", "How do I submit my application?", "Upload your resume on the home page, then complete the four steps. Applicants do not need an account.", "كيف أرسل طلبي؟", "ارفع سيرتك الذاتية في الصفحة الرئيسية ثم أكمل الخطوات الأربع. لا يحتاج المتقدم إلى حساب.", {fr:["CV","postuler","candidature"],en:["resume","apply","application"],ar:["السيرة","طلب","تقديم"]}),
  entry("documents", "documents", "Quels documents puis-je envoyer ?", "Le CV est obligatoire. La lettre de motivation est facultative. Les formats PDF, DOC et DOCX sont acceptés dans la limite indiquée par le formulaire.", "Which documents can I send?", "A resume is required. A cover letter is optional. PDF, DOC and DOCX files are accepted within the limit shown on the form.", "ما المستندات التي يمكنني إرسالها؟", "السيرة الذاتية إلزامية ورسالة التحفيز اختيارية. تُقبل ملفات PDF وDOC وDOCX ضمن الحد المبين في النموذج.", {fr:["document","lettre","format"],en:["document","cover letter","format"],ar:["مستند","رسالة","صيغة"]}),
  entry("account", "accounts", "Dois-je créer un compte pour postuler ?", "Non. Le parcours candidat fonctionne sans compte. Seuls les employés et l’administrateur se connectent avec des accès créés par l’administrateur.", "Do I need an account to apply?", "No. Applicants apply without an account. Only employees and the administrator sign in with access created by the administrator.", "هل أحتاج إلى حساب للتقديم؟", "لا. يتقدم المرشحون دون حساب. يسجل الموظفون والمسؤول فقط الدخول ببيانات ينشئها المسؤول.", {fr:["compte","connexion","candidat"],en:["account","login","applicant"],ar:["حساب","دخول","مرشح"]}),
  entry("employee-login", "accounts", "Comment un employé se connecte-t-il ?", "L’employé utilise son nom, son prénom et le mot de passe transmis par l’administrateur sur la page de connexion unique.", "How does an employee sign in?", "The employee uses their last name, first name and the password supplied by the administrator on the single sign-in page.", "كيف يسجل الموظف الدخول؟", "يستخدم الموظف اسم العائلة والاسم الشخصي وكلمة المرور التي قدمها المسؤول في صفحة الدخول الموحدة.", {fr:["employé","connexion","mot de passe"],en:["employee","login","password"],ar:["موظف","دخول","كلمة المرور"]}),
  entry("leave", "support", "Comment demander un congé ?", "Depuis l’espace employé, ouvrez Congés, choisissez les dates et envoyez la demande. Le solde est calculé côté serveur hors week-ends et jours fériés configurés.", "How do I request leave?", "In the employee area, open Leave, choose the dates and submit. The balance is calculated by the server excluding weekends and configured public holidays.", "كيف أطلب إجازة؟", "من مساحة الموظف افتح الإجازات واختر التواريخ ثم أرسل الطلب. يحسب الخادم الرصيد باستثناء عطلات نهاية الأسبوع والعطل المسجلة.", {fr:["congé","solde","absence"],en:["leave","balance","absence"],ar:["إجازة","رصيد","غياب"]}),
  entry("language", "languages", "Quelles langues sont disponibles ?", "Workcrute est disponible en français, anglais et arabe. L’arabe utilise une mise en page complète de droite à gauche.", "Which languages are available?", "Workcrute is available in French, English and Arabic. Arabic uses a complete right-to-left layout.", "ما اللغات المتاحة؟", "يتوفر Workcrute بالفرنسية والإنجليزية والعربية، مع عرض عربي كامل من اليمين إلى اليسار.", {fr:["langue","français","arabe"],en:["language","French","Arabic"],ar:["لغة","العربية","الفرنسية"]}),
  entry("privacy", "privacy", "Comment mes données sont-elles protégées ?", "Les accès sont contrôlés, les mots de passe sont hachés et les documents ne sont accessibles qu’aux personnes autorisées. Ne partagez jamais votre mot de passe.", "How is my data protected?", "Access is controlled, passwords are hashed and documents are available only to authorised people. Never share your password.", "كيف تتم حماية بياناتي؟", "تخضع الصلاحيات للرقابة وتُشفّر كلمات المرور ولا تتاح المستندات إلا للمصرح لهم. لا تشارك كلمة مرورك أبداً.", {fr:["données","sécurité","confidentialité"],en:["data","security","privacy"],ar:["بيانات","أمان","خصوصية"]}),
];
